### PR TITLE
feat(bookmarks): Bookmark toggling works in discovery OZBE8

### PR DESCRIPTION
**Pull request by blaino**
OZBE8 = ozone-development/ozp-backend#8

### CODE REVIEW

**Comment by blaino** [comment]
@arw180 have a look. 

So the ticket reads "Bookmark listings works on Discovery page". I have taken this to mean toggling the bookmarks on and off, and being able to confirm that change either via swagger or hud. Maybe there is some other aspect of bookmark "listing" that I don't yet know about?

**Comment by rpokorny** [comment]
What change in behavior results from these changes?  It seems to me like this code would effectively do the exact same thing as it did before.

**Comment by blaino** [comment]
@rpokorny this is a refactor to work with the Django Rest Framework backend. I'm hoping the behavior does not change. (This is not a pull request into master, but into the new-backend branch).

**Comment by rpokorny** [comment]
OK, I see it now.  The important part is that you match on `x.listing.id` but then retrieve (effectively) just `x.id`, right?

**Comment by arw180** [comment]
tested :+1:

**Comment by blaino** [comment]
@rpokorny , right.

**Pull request merged**
