### PR TITLE
fix(Search Description): added and where nessecery between labels

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat @hoganmaps please have a look when available

**Comment by clarkjefcoat** [comment]
Multiple agencies should say "or".  Multiple listing types should say "or".

**Comment by wski** [comment]
@clarkjefcoat new commit fixes this

**Comment by clarkjefcoat** [comment]
Where you use "or" I don't think you need to make it plural.

image

Shouldn't the above say "with the type Web Application or Widget in the organization ... with the categories ...".  Change "types" to "type" and "organizations" to "organization".  But leave "categories" as is.

Also why isn't there a space in front of "in" and in front of "with"?

**Comment by wski** [comment]
@clarkjefcoat

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by hoganmaps** [comment]
:+1: this is acceptable

**Pull request merged**
