### PR TITLE
567 - fixed by adding agency for

### PR DESCRIPTION
**Pull request by rkenyon1969**
Please review:

@clarkjefcoat 
@wski

### CODE REVIEW

**Comment by rkenyon1969** [comment]
**Update: simplified code to only pull Listing.agencyShort instead of all of Listing**

var listingAgencyShort = GlobalListingStore.getById(changeLog.listing.id).agencyShort;
        return (
            <div>
                <AuthorLink author={changeLog.author} />
                <span> approved </span>
                { this.props.listingName } for { listingAgencyShort }
            </div>

**Comment by rkenyon1969** [comment]
Placing this on-hold until update by Manny to backend is complete. Update will add agency short_name to listing data already being pulled making the additional call to GlobalListingStore redundant. 

@clarkjefcoat 
@wski 
@akonsowski 
@mannyrivera2010

**Comment by mannyrivera2010** [comment]
````
index 148f04c..0fece20 100644
--- a/app/js/components/shared/ChangeLog.jsx
+++ b/app/js/components/shared/ChangeLog.jsx
@@ -85,7 +85,7 @@ var OrgApprovalChangeLog = React.createClass({
             <div>
                 <AuthorLink author={changeLog.author} />
                 <span> approved </span>
-                { this.props.listingName } for { changeLog.listing.agency }
+                { this.props.listingName } for { changeLog.listing.agency.shortName }
             </div>
         );
     }

````

**Comment by rkenyon1969** [comment]
I've updated my branch and pushed changes per Manny's comment

**Comment by rkenyon1969** [comment]
Please review

@clarkjefcoat 
@wski 
@mannyrivera2010

**Comment by clarkjefcoat** [comment]
Tested in conjunction with https://github.com/ozone-development/ozp-backend/pull/142

Nice.  :+1:

**Comment by mannyrivera2010** [comment]
:+1:

**Pull request merged**
