### PR TITLE
fix(Search)Made search result tab to main content

### PR DESCRIPTION
**Pull request by SOAP1914**
@wski @akonsowski @rkenyon1969

### CODE REVIEW

**Comment by akonsowski** [comment]
:-1: when focus changes and goes to the listings a lot of things can happen. like going back a page if you hit backspace, or typing with no effect in the search bar. i would suggest changing focus after hitting enter or something like that

**Comment by SOAP1914** [comment]
Thanks @akonsowski for the bug catch.

**Comment by wski** [comment]
:+1:

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
