### PR TITLE
fix(Toolbar): disable notification style when no notifications are present #282

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@arw180 and @clarkjefcoat please have a look.

**Comment by arw180** [comment]
This is user facing, and as such should use `feat` or `fix`, not `chore` in the commit message so it shows up in the changelog

**Comment by arw180** [comment]
Maybe my browser is caching CSS, but I'm not seeing any changes with this branch

**Comment by blaino** [comment]
ditto. not seeing any changes after pulling down this branch.

**Comment by wski** [comment]
Note: when testing please be sure to use the OZP-React-Commons PR that's in progress as well

**Comment by blaino** [comment]
Pulled and tested with commons. Works with a caveat. Intermittently, when clicking on the help icon, the notification icon momentarily (way less than a second) highlights. Despite this problem, I'm still saying :+1:

**Comment by wski** [comment]
rebased

**Comment by arw180** [comment]
Others have tested, so not repeating that. Code and commit look good. :+1:

**Pull request merged**
