### PR TITLE
fix(createEdit): Maintain preview without undeleteable chars #324

### PR DESCRIPTION
**Pull request by blaino**
Commit db76913 fixed the undeleteable character, but introduced a bug
where preview of the listing is no longer updated for What's New. Use
lodash's isEqual to do a deep comparison of props; update component if
there is a change for anything in props. Do this instead of modifying
_onChange() which, as evidenced by this bug, is more dangerous.

### CODE REVIEW

**Comment by blaino** [comment]
@wski Need the first review. Since this monkeys with shouldComponentUpdate() a bit, please test on you lesser machine to check for performance problems.

**Comment by wski** [comment]
You spelled engineering marvel wrong in your last comment, but other than that I tested on my amazing machine on Chrome and Slowfari (Safari) and everything checks out :+1:

**Comment by blaino** [comment]
@arw180, need second review, when you get a chance.

**Comment by arw180** [comment]
didn't repeat tests that others did, but code and commit look good :+1:

**Pull request merged**
