### PR TITLE
fix(Center_508_Tour)Make bootstrap Tour modal 508 compliance#597

### PR DESCRIPTION
**Pull request by SOAP1914**

### CODE REVIEW

**Comment by SOAP1914** [comment]
@wski @akonsowski @clarkjefcoat

**Comment by clarkjefcoat** [comment]
For next time please remember to put a colon after your closing paren.  You commit message should have been "fix(Center_508_Tour): Make bootstrap Tour modal 508 compliance #597"

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by wski** [comment]
:+1:

**Pull request merged**
