### PR TITLE
fix(Index): componenet will mount and will receive props were both ru…

### PR DESCRIPTION
**Pull request by akonsowski**
…nning when the app loads the review. the reviews will still load when will receive prrops is called removed will load #546

### CODE REVIEW

**Comment by akonsowski** [comment]
@wski @SOAP1914 @rkenyon1969

**Comment by wski** [comment]
I'll need to take a closer look at this, judging by the comment if there is no review found in the store it will fail.

**Comment by wski** [comment]
:+1: but I think @tdressel should do some testing on this before we merge

**Comment by rkenyon1969** [comment]
:+1:

**Pull request merged**
