### PR TITLE
fix(Metrics): listing review view, and review fixed

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat @gziskind

**Comment by clarkjefcoat** [comment]
:+1: for the code change.  Tested in chrome.

We will need to let program management know that the metrics being reported have changed.

**Comment by gziskind** [comment]
I'm still getting multiple events from viewing a review a single time

**Comment by gziskind** [comment]
:+1: looks great

**Pull request merged**
