### PR TITLE
(fix)Listing Type, Organizations dropdown and side Nav

### PR DESCRIPTION
**Pull request by SOAP1914**

### CODE REVIEW

**Comment by SOAP1914** [comment]
@arw180 @wski @blaino

**Comment by clarkjefcoat** [comment]
:+1:  I will take your word that this fixes JAWS issues.  It doesn't seem to have broken anything.

**Comment by SOAP1914** [comment]
Thanks @clarkjefcoat lol Its alot of tabIndex I know. I've tested it on iOS VoiceOver and it worked fine.

**Comment by wski** [comment]
I belive the tab index values are not correct long term, should use as follows

```
<SelectBox tabIndex="1">
   <Option tabIndex="2">Something Here</Option>
   <Option tabIndex="3">Something Here</Option>
   <Option tabIndex="4">Something Here</Option>
   <Option tabIndex="5">Something Here</Option>
</SelectBox>
```

If this is just for testing though, it should be fine. From what I can tell tab index defines  the order at which things are shown as you tab through an application with JAWS. With that in mind we should never have repeating tab indexes.

**Comment by bhalt** [comment]
can this branch be deleted @SOAP1914?

**Comment by SOAP1914** [comment]
yes

**Pull request merged**
