### PR TITLE
feat(lt IE 10): Redirect users below IE10 away

### PR DESCRIPTION
**Pull request by wski**
Related ozp-react-commons PR needs to be checked out for this to work

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat

**Comment by clarkjefcoat** [comment]
Travis CI failures are due to related bug fixed with #520

**Comment by clarkjefcoat** [comment]
Confirm IE9 works.  IE8 shows a blank screen for reasons that seem unrelated to this bug fix.  :+1:

**Comment by SOAP1914** [comment]
good old IE :+1:

**Pull request merged**
