### PR TITLE
fix(*): Eliminate many warnings. #423

### PR DESCRIPTION
**Pull request by blaino**
It took me a while, but I found one change that was causing the unit test failures. I backed out the  changes to RecentActivity. Also, I had branched off of master before Ryan's big refactor, and that was causing problems with the unit tests for AllListings and OrgListings.

### CODE REVIEW

**Comment by blaino** [comment]
@wski, @arw180 please have a look when you get a chance.

**Comment by wski** [comment]
:+1:

**Comment by blaino** [comment]
@arw180, gentle reminder. 

@clarkjefcoat, you might want to take a look too.

**Comment by arw180** [comment]
:+1:

**Pull request merged**
