### PR TITLE
(fix) 617 display wrong notification

### PR DESCRIPTION
**Pull request by dylankolson**
Fix for issue #617 where the see more notifications when clicked on displayed the wrong notification in the right of the pop up window.

### CODE REVIEW

**Comment by wski** [comment]
Good catch, We will need to reverse the order further up. Currently the backend seems to be sending us notifications oldest first, and we want to get the reverse of that. In addition to removing the bad `reverse()` we should reverse the result in the webapi instead so that we see the newest notifications first. 

If you'd like I can tack this onto your PR

**Comment by dylankolson** [comment]
@wski  Sure, the reason I removed it was I was working on adding a sort in ozp-backend for accessing the user notifications and it still displayed the wrong order on the sidebar but not in the navbar. 

https://github.com/dylankolson/ozp-backend/commit/be0abc117029024eaf352b82db012eefba791da2
https://github.com/ozone-development/ozp-backend/issues/160

**Comment by wski** [comment]
Gotcha, if that's planned to go in soon I think this PR would be fine :+1: and we can hold off on adding anything to our webapi on center & hud until a sort is working in the backend. @mannyrivera2010 @clarkjefcoat

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
