### PR TITLE
Help modal styling

### PR DESCRIPTION
**Pull request by bhalt**
Clean up styling, layout, and language to maintain consistency on the Help Modal across the platform.

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
Can you remove APP_TITLE from line 4 of helpmodal.jsx?

jshint gives a warning based on the changes you have made:
```
WARNING in ./app/js/components/NavBar/helpmodal.jsx
jshint results in errors
  'APP_TITLE' is defined but never used. @ line 4 char 35
    var { HELP_URL, HELPDESK_ADDRESS, APP_TITLE } = require('ozp-react-commons/OzoneConfig');
```

**Comment by wski** [comment]
@clarkjefcoat  it could be left, should be used for the tour button. Or removed for now

**Comment by bhalt** [comment]
Done - please review.

**Comment by bhalt** [comment]
@wski I checked, and APP_TITLE was being used for custom Help modal titles -- which I had removed since they weren't a part of the original design. The tour button text is hard coded. I went ahead and removed the var for APP_TITLE.

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by blaino** [comment]
:+1:

**Comment by wski** [comment]
@bhalt Cool, I was just suggesting we do not hard code the tour button but instead use the `APP_TITLE` in the future

**Pull request merged**
