### PR TITLE
feat(Interactive Tour): Added interactive tour to center.

### PR DESCRIPTION
**Pull request by wski**
@arw180 @clarkjefcoat

### CODE REVIEW

**Comment by blaino** [comment]
Clicking 'no thanks' does not end the tour. If you refresh or go to hud and come back after clicking 'no thanks', the tour intro continues to present itself. If you start the tour and click 'end tour', then the tour is gone for real.

**Comment by wski** [comment]
Fixed

**Comment by blaino** [comment]
Concur. Pulled the last commit. Problem gone.

**Comment by blaino** [comment]
:+1:

**Comment by wski** [comment]
Known issue #504 not fixed in this PR, will be fixed in next PR.

**Comment by tonyalletag** [comment]
:+1:

**Pull request merged**
