### PR TITLE
add(headings and focus)to the sidebar and model #484

### PR DESCRIPTION
**Pull request by SOAP1914**
add focus (tabIndex) and offscreen headings so JAWS can read when a user is looking for all headings within the app.

### CODE REVIEW

**Comment by SOAP1914** [comment]
@blaino @arw180 @wski when you have time 2 look at it

**Comment by blaino** [comment]
I pulled and clicked around. Doesn't seem to break anything. :+1:

**Comment by SOAP1914** [comment]
Use an **off screen** technique to remove content from visible display, but still available to screen reader users:

**Comment by wski** [comment]
looks good, In the future it would be cool to experiment with `display:none;` for the offscreen elements if the screen reader can read hidden elements. :+1:

**Comment by SOAP1914** [comment]
I would love to use [display: none] but after doing some research this works for Center and JAWS 
 
https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/

**Pull request merged**
