### PR TITLE
Added reporting of agency information when application launches are r…

### PR DESCRIPTION
**Pull request by gziskind**
…eported

This change will allow the metrics application to be aware of the creating agency when an application is launched.

### CODE REVIEW

**Comment by wski** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Will we also be adding tickets to track when applications are launched from HUD or Webtop?

Is there a corresponding ticket that goes with this pr?

**Comment by wski** [comment]
@gziskind can you create a issue for this so that we can track it

**Comment by gziskind** [comment]
sure #330

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
