### PR TITLE
fix(DetailView): Usage Requirements now wraps long text with no spaces #343

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat @blaino

**Comment by clarkjefcoat** [comment]
:+1:  This force wraps in the same way as What's New

**Comment by blaino** [comment]
So we want to cut words right in the middle? 
screen shot 2015-08-25 at 10 04 44 am

**Comment by wski** [comment]
This is the only reliable way to break super long strings that I could find. Though it is odd that it's wrapping words that could be brought to the next line, it's the only solution I could find that was compliant with all browsers

**Comment by blaino** [comment]
I'm guessing that a more subtle approach could be found and we should look for it, but this gets rid of immediate ugliness. :+1:

**Pull request merged**
