### PR TITLE
Fix empty listing type

### PR DESCRIPTION
**Pull request by blaino**
This change isolates the delay to select2input fields only - tag inputs aren't changed. @wski, please take a first look.

### CODE REVIEW

**Comment by wski** [comment]
Is there a reason for merging master in verses rebasing master into your branch? If not please rebase to avoid multiple commits.

**Comment by blaino** [comment]
@wski , No, no good reason. Should have rebased master into my branch. After talking with Alan, we've decided it's not worth trying to fix - as the fix would lose this conversation's history.

**Comment by wski** [comment]
Verified that the tag fix works, unnecessary cancel timeouts and variables were removed. Everything looks :+1:

**Comment by blaino** [comment]
@clarkjefcoat , need a second reviewer.

**Comment by clarkjefcoat** [comment]
:+1:  (Could not test in IE when choosing "Submit a Listing" from the HUD dropdown due to an unrelated bug.  Otherwise, it looks good.)

**Comment by clarkjefcoat** [comment]
This fixes #328 as well.

**Pull request merged**
