### PR TITLE
fix(Tour): Close tour at end of tour

### PR DESCRIPTION
**Pull request by wski**
@tonyalletag @clarkjefcoat

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
IE10 allows me to click 'Next' at the end of the tour.  In that case the modal is not closed.

**Comment by wski** [comment]
I think that should be opened as a separate bug, the next button should not be clickable

**Comment by clarkjefcoat** [comment]
:+1:

New Issue Created #575

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
