### PR TITLE
feat(Notifications): increase notification length to 600 characters

### PR DESCRIPTION
**Pull request by wski**
@clarkjefcoat @mannyrivera2010 @akonsowski

### CODE REVIEW

**Comment by akonsowski** [comment]
:+1:  but it looks like this 
image

**Comment by clarkjefcoat** [comment]
FYI, the database field that holds the notification message has a maximum length of 4096.  So we could accommodate messages even longer than the current 600 without changing the database if requirements change.

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by wski** [comment]
@clarkjefcoat yeah I noticed that, I'm not sure we want to. @bhalt had mentioned she didn't want anything too high last time we spoke.

**Pull request merged**
