### PR TITLE
App notifications

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat @rkenyon1969

**Comment by wski** [comment]
Make sure to pull latest, had forgotten a filter for past notifications

**Comment by wski** [comment]
Reverted changes from @akonsowski, made some other changes

**Comment by wski** [comment]
Will rebase once I get the thumbs up

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by wski** [comment]
[](http://38.media.tumblr.com/9a49131d89b12a337534800918504294/tumblr_inline_nzb6a3hkJG1rp5ay0_500.gif) Rebasing done

**Comment by akonsowski** [comment]
:+1: - but i was wondering if when we add functionality for peer to peer and agency if we should add the name of the user or agency that it is coming from.

**Comment by rkenyon1969** [comment]
:+1:  - Suggestion - change "Expired" to "Expires" if not yet expired

**Pull request merged**
