### PR TITLE
578 management

### LINKED ISSUE #578: Listing Management - Recent Activity tabs links do not work
The links of the left of the Recent Activity tab do not work.  Clicking them takes you to the general Listing Management page, but does not automatically select the subset that you chose.

### PR DESCRIPTION
**Pull request by akonsowski**
…issue where reacent activity was not linking to all listings this pull request will fix #578  and #619 but @mannyrivera2010 deleted counts will need a backend change to count deleted apps

@rkenyon1969 @wski @SOAP1914 @clarkjefcoat

### CODE REVIEW

**Comment by SOAP1914** [comment]
monday I'll look at this for you @akonsowski

**Comment by SOAP1914** [comment]
👍 (looked at it on @akonsowski cpu ) works great

**Comment by wski** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Pull request merged**
