### PR TITLE
Create/Edit Page - Invalid portion markings are allowed #588

### PR DESCRIPTION
**Pull request by rkenyon1969**
@clarkjefcoat 
@wski

Please review and test.

### CODE REVIEW

**Comment by rkenyon1969** [comment]
#588

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by rkenyon1969** [comment]
@wski - need thumb

**Comment by wski** [comment]
This will block normal users from putting in the wrong portion markings, however we should have backend validation as this is easily bypassed by deleting the readOnly attribute in the web inspector 👍

**Comment by clarkjefcoat** [comment]
@wski - Good thinking.  We have added some basic backend validation with https://github.com/ozone-development/ozp-backend/pull/151

**Comment by rkenyon1969** [comment]
Matt's point is important. Manny has a separate ticket that addresses this issue on the backend.

@mannyrivera2010

**Pull request merged**
