### PR TITLE
(fix)Top Left Nav and Testing Form labels

### PR DESCRIPTION
**Pull request by SOAP1914**

### CODE REVIEW

**Comment by blaino** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
:+1:
Will a hidden-span be added to the notifications icon in a separate pull request?

**Comment by SOAP1914** [comment]
Yes (separate PR) the notification is in the ozp-react-commons repo

**Comment by bhalt** [comment]
can this branch be deleted @SOAP1914?

**Comment by SOAP1914** [comment]
yes

**Pull request merged**
