### PR TITLE
feat(Discovery): Scroll to top on search results #289

### PR DESCRIPTION
**Pull request by wski**
@blaino @clarkjefcoat @arw180

### CODE REVIEW

**Comment by blaino** [comment]
:+1: Pulled and tried it out locally - works as expected. 

@clarkjefcoat , second review please.

**Comment by arw180** [comment]
Please `rebase -i` this down to a single commit and use `feat` instead of `chore` for the commit msg so it shows up in the changelog, as this is user-facing

**Comment by arw180** [comment]
Rebase needs work - still see two commits

**Comment by wski** [comment]
I am aware, I'll reply here when I'm ready for you to check

**Comment by wski** [comment]
Rebased to one commit

**Comment by arw180** [comment]
And what a beautiful rebase it was. :+1:

**Pull request merged**
