### PR TITLE
fix(Detail View): Word wrap forced for what's new #207

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@blaino and @arw180 please have a look

**Comment by arw180** [comment]
User-facing, use `fix` instead of `chore` in commit msg for changelog visibility

**Comment by blaino** [comment]
I tried to update a What's New field to have enough characters to test this. Regardless of what I submit, I get "Not provided!" in the preview details tab.

**Comment by wski** [comment]
This fix simply adds the css property word-wrap, if there are issues submitting the form it may be related to a different bug. I'll try to reporduce.

**Comment by wski** [comment]
rebased

**Comment by arw180** [comment]
Didn't do a full test, but :+1:

**Comment by blaino** [comment]
Pulled and tested on chrome with long url. :+1:

**Pull request merged**
