### PR TITLE
Listing Management - Recent Activity should show icons #587

### PR DESCRIPTION
**Pull request by rkenyon1969**
@clarkjefcoat 
@mannyrivera2010

### CODE REVIEW

**Comment by wski** [comment]
👍

**Comment by rkenyon1969** [comment]
@clarkjefcoat - thumb up?

**Comment by akonsowski** [comment]
what is the variable var ttt = this.state.listing; used for

**Comment by rkenyon1969** [comment]
var ttt was a test variable that i didn't remove. thanks!

**Comment by clarkjefcoat** [comment]
Tested in conjunction with https://github.com/ozone-development/ozp-backend/pull/157

:+1:

**Pull request merged**
