### PR TITLE
Fix(Listing): Administration Tab: Bookmark icon no change unless page refresh #596

### PR DESCRIPTION
**Pull request by rkenyon1969**
#596 
@clarkjefcoat 
@wski 
@akonsowski 
@mannyrivera2010

### CODE REVIEW

**Comment by rkenyon1969** [comment]
dependent: https://github.com/ozone-development/ozp-backend/pull/166

**Comment by akonsowski** [comment]
@rkenyon1969 im unsure what these changes are doing the changes to backend prevent the icon from being changed by throwing a 404 error. I think there should be a warning that pops up stating the application is disabled and cant be changed.

**Comment by akonsowski** [comment]
:-1:  was not working when i tested it bookmarked an app disabled the app refreshed the page bookmark the app was still not bookmarked

**Comment by akonsowski** [comment]
:+1:

**Comment by rkenyon1969** [comment]
@clarkjefcoat 
@wski 
@akonsowski 
@mannyrivera2010

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by akonsowski** [comment]
:-1:
bookmark an app then disable it
refresh the page 
enable and uncheck the bookmark gives an error
BookmarkButton.jsx:43 Uncaught TypeError: Cannot read property 'id' of undefined

**Comment by rkenyon1969** [comment]
@akonsowski  - please test again

**Comment by akonsowski** [comment]
:-1: the button now appears to let you bookmark when the application is disabled. if you disable the listing bookmark and reenable it will still show as bookmarked however when you check in hud the bookmark is not there. go back to center and the listing is not bookmarked

**Comment by akonsowski** [comment]
:+1: i would suggest squishing some of those branches though

**Comment by rkenyon1969** [comment]
This has been rebased. Please review again to make sure nothing changed because of rebasing. - thank you,

@clarkjefcoat 
@wski 
@akonsowski 
@mannyrivera2010

**Comment by akonsowski** [comment]
:-1: the rebase looks off. it should not have all the commits still it should only have the ones that you made not the ones others made as well.

**Comment by rkenyon1969** [comment]
@akonsowski - please review again

**Pull request merged**
