### PR TITLE
chore(Create Edit): only replace spaces with encoded spaces if spaces exist #260

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by rpokorny** [comment]
I said it when this issue first came up, but I'll say it again.  I strongly believe that the correct way to address this is to not allow spaces in URL fields at all.  No real-world URL will have spaces, since spaces are not allowed in URLs.  Doing validation of that would be much simpler than all this escaping/unescaping gymnastics.

**Comment by wski** [comment]
Agreed, Clark and I talked for a while yesterday and we've came to the agreement that we would only correct their mistake if they added spaces and from them on only display the encoded url in hopes they realize the mistake. 

We've simplified it quite a bit because the hole we were digging by trying to decode and encode all over the place was very deep.

**Comment by rpokorny** [comment]
That... isn't quite what I was saying.  I'm saying it should fail to validate if the URI is invalid.  Spaces are not valid characters in a URI.  Thus if they put a space in the URI text field it turns red and they can't save.  If they are trying to maunally type in a URI that should include %20s, they can (and should) encode it themselves

**Comment by wski** [comment]
I understood that but from what I've been told it's a problem with our end user that happens a lot so we are trying to ease up on some of their confusion. I try to assume my mom is the same as an end user and I cannot see her figuring out how to encode a URL I think she would give up on creating all together

**Comment by rpokorny** [comment]
I don't see low-tech end users writing URIs by hand (as opposed to copy/pasting them) but ok

**Pull request merged**
