### PR TITLE
fix(Detail View): Truncation to wrapped link #274

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat and @blaino please have a look

**Comment by arw180** [comment]
User facing, please change commit message to use `fix` instead of `chore` so we get it into the changelog

**Comment by blaino** [comment]
Pulled. Tested locally with chrome. Works as expected. :+1: after fixing the commit message.

**Comment by wski** [comment]
closing because I fixed this, along with another instance. This will only cause merge conflicts

**Pull request closed without merging**
