### PR TITLE
fix(_quickviewscss): changed height and width and padding to make it …

### PR DESCRIPTION
**Pull request by akonsowski**
…fit the 8 character name #583 i tried to fix the padding so it look even.

@bhalt, @clarkjefcoat @wski @rkenyon1969

### CODE REVIEW

**Comment by wski** [comment]
👍

**Comment by rkenyon1969** [comment]
:+1:

**Comment by bhalt** [comment]
@akonsowski Actually, it would be great to not have a height/width on this Org element, since that forces us to set a custom size every time we run into this issue again with a longer Org name. The element should have a dynamic width to flex with the content, rather than being boxed into certain pixel sizes.

To prevent word wrap when there is a dash, you can add 
```white-space: nowrap;```

to the `.company` and remove the other CSS added. Let me know if you need anything else!

**Comment by akonsowski** [comment]
@bhalt that seems to have done the trick Thank you.

**Pull request merged**
