### PR TITLE
fix(Discovery): Makes searches with only orgs return results

### PR DESCRIPTION
**Pull request by clarkjefcoat**
Issue #334

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
@arw180 - I'd like to get this in tomorrow's build.

**Comment by arw180** [comment]
Tested locally - confirmed it fixes issue #334. Can @blaino or @wski take a quick look and do a visual inspection?
:+1:

**Comment by blaino** [comment]
I pulled and tested. The no results found goes away, but "/home///Web%20Application/" yields a search for "Web Application" whereas "/home/Web%20Application/" yields a search for "Web" or "Application" - one gray label as opposed to two. Also, "/home///Web%20Application/" doesn't put anything in the search box so you can't clear it out with by clicking X. 

I'm wondering where these triple slash urls are coming from in the first place.  When I click share I get a link like: "/home/air%20bread///" not  "/home///air%20bread/". "/home/bread%20mail///" correctly yields a search for "bread" or "mail" on ci-develop currently. 

I must be misunderstanding something.

**Comment by blaino** [comment]
Clark straightened me out. Three slashes: /<category>/<search>/<web application>/<organization>. I get it now.

**Comment by wski** [comment]
I'd like to pull this down locally before deploying it, the removal of some initial data setting and moving stuff to componentWillUnmount seems weird. If we are relying on the componentWillUnmount to display data on that component that would be bad. Will talk with @clarkjefcoat and make sure I fully understand the changes

**Comment by wski** [comment]
:+1: confusing git diff got me.

**Pull request merged**
